BookGUI/Components/CountriesListViewComponent.cs
using BookApiProject.Services;
using BookGUI.Models;
using BookGUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookGUI.Components
{
    public class CountriesListViewComponent : ViewComponent
    {
        ICountryRepositoryGUI _countryRepository;

        public CountriesListViewComponent(ICountryRepositoryGUI countryRepository)
        {
            _countryRepository = countryRepository;
        }

        public IViewComponentResult Invoke()
        {
            var countries = _countryRepository.GetCountries().
                                                OrderBy(c => c.Name).
                                                Select(x => new { Id = x.Id, Value = x.Name });

            var countriesList = new CountrySelectList
            {
                CountriesList = new SelectList(countries, "Id", "Value")
            };

            return View("_CountriesList", countriesList);
        }
    }
}

BookGUI/Controllers/AuthorsController.cs
using BookApiProject.Dtos;
using BookApiProject.Models;
using BookGUI.Services;
using BookGUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace BookGUI.Controllers
{
    public class AuthorsController : Controller
    {
        IAuthorRepositoryGUI _authorRepository;
        ICountryRepositoryGUI _countryRepository;
        ICategoryRepositoryGUI _categoryRepository;

        public AuthorsController(IAuthorRepositoryGUI authorRepository, ICountryRepositoryGUI countryRepository,
            ICategoryRepositoryGUI categoryRepository)
        {
            _authorRepository = authorRepository;
            _countryRepository = countryRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {
            var authors = _authorRepository.GetAuthors();

            if (authors.Count() <= 0)
            {
                ViewBag.Message = "There was a problem retrieving authors from the database or no author exists";
            }

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(authors);
        }

        public IActionResult GetAuthorById(int authorId)
        {
            var author = _authorRepository.GetAuthorById(authorId);
            if (author == null)
            {
                ModelState.AddModelError("", "Some kind of error getting author");
                ViewBag.Message = $"There was a problem retrieving author from the " +
                                    $"database or no author with id {authorId}  exists";
                author = new AuthorDto();
            }

            var country = _countryRepository.GetCountryOfAnAuthor(authorId);
            if (country == null)
            {
                ModelState.AddModelError("", "Some kind of error getting country");
                ViewBag.Message += $"There was a problem retrieving country from the " +
                                    $"database or no country for author with id {authorId} exists";
                country = new CountryDto();
            }

            var bookCategories = new Dictionary<BookDto, IEnumerable<CategoryDto>>();
            var books = _authorRepository.GetBooksByAuthor(authorId);
            if (books.Count() <= 0)
            {
                ViewBag.BookMessage = $"No books for {author.FirstName} {author.LastName} exists.";
            }

            foreach(var book in books)
            {
                var categories = _categoryRepository.GetAllCategoriesOfABook(book.Id);
                bookCategories.Add(book, categories);
            }

            var authorCountryBooksCategoriesViewModel = new AuthorCountryBooksCategoriesViewModel
            {
                Author = author,
                Country = country,
                BookCategories = bookCategories
            };

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(authorCountryBooksCategoriesViewModel);
        }

        [HttpGet]
        public IActionResult CreateAuthor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateAuthor(int CountryId, Author author)
        {
            using (var client = new HttpClient())
            {
                var countryDto = _countryRepository.GetCountryById(CountryId);

                if (countryDto == null || author == null)
                {
                    ModelState.AddModelError("", "Invalid country or author. Cannot create author!");
                    return View(author);
                }

                author.Country = new Country
                {
                    Id = countryDto.Id,
                    Name = countryDto.Name
                };

                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.PostAsJsonAsync("authors", author);
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var newAuthorTask = result.Content.ReadAsAsync<Author>();
                    newAuthorTask.Wait();

                    var newAuthor = newAuthorTask.Result;
                    TempData["SuccessMessage"] = $"Author {newAuthor.FirstName} {newAuthor.LastName} " +
                                                $"was successfully created.";
                    return RedirectToAction("GetAuthorById", new { authorId = newAuthor.Id });
                }

                ModelState.AddModelError("", "Author not created");
            }

            return View(author);
        }

        [HttpGet]
        public IActionResult UpdateAuthor(int CountryId, int authorId)
        {
            var authorDto = _authorRepository.GetAuthorById(authorId);
            var countryDto = _countryRepository.GetCountryOfAnAuthor(authorId);

            Author author = null;
            if (countryDto == null || authorDto == null)
            {
                ModelState.AddModelError("", "Invalid country or author. Cannot update author!");
                author = new Author();
            }
            else
            {
                author = new Author
                {
                    Id = authorDto.Id,
                    FirstName = authorDto.FirstName,
                    LastName = authorDto.LastName,
                    Country = new Country
                    {
                        Id = countryDto.Id,
                        Name = countryDto.Name
                    }
                };
            }

            return View(author);
        }

        [HttpPost]
        public IActionResult UpdateAuthor(int CountryId, Author authorToUpdate)
        {
            var countryDto = _countryRepository.GetCountryById(CountryId);

            if (countryDto == null || authorToUpdate == null)
            {
                ModelState.AddModelError("", "Invalid country, or author. Cannot update author!");
            }
            else
            {
                authorToUpdate.Country = new Country
                {
                    Id = countryDto.Id,
                    Name = countryDto.Name
                };

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:60039/api/");
                    var responseTask = client.PutAsJsonAsync($"authors/{authorToUpdate.Id}", authorToUpdate);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["SuccessMessage"] = "Author updated";
                        return RedirectToAction("GetAuthorById", new { authorId = authorToUpdate.Id });
                    }

                    ModelState.AddModelError("", "Unexpected Error. Author Not Updated");
                }
            }

            return View(authorToUpdate);
        }

        [HttpGet]
        public IActionResult DeleteAuthor(int authorId)
        {
            var authorDto = _authorRepository.GetAuthorById(authorId);
            if (authorDto == null)
            {
                ModelState.AddModelError("", "Invalid author!");
                authorDto = new AuthorDto();
            }

            return View(authorDto);
        }

        [HttpPost]
        public IActionResult DeleteAuthor(string authorFirstName, string authorLastName, int authorId)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.DeleteAsync($"authors/{authorId}");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = $"Author {authorFirstName} {authorLastName} was successfully deleted.";

                    return RedirectToAction("Index");
                }

                if ((int)result.StatusCode == 409)
                {
                    ModelState.AddModelError("", $"Author {authorFirstName} {authorLastName} cannot be deleted because " +
                                                $"it is used by at least one book");
                }
                else
                {
                    ModelState.AddModelError("", "Some kind of error. Author not deleted!");
                }
            }

            var authorDto = _authorRepository.GetAuthorById(authorId);
            return View(authorDto);
        }
    }
}

BookGUI/Controllers/CountriesController.cs
using BookApiProject.Dtos;
using BookApiProject.Models;
using BookGUI.Services;
using BookGUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace BookGUI.Controllers
{
    public class CountriesController : Controller
    {
        ICountryRepositoryGUI _countryRepository;
        IAuthorRepositoryGUI _authorRespository;

        public CountriesController(ICountryRepositoryGUI countryRepository, IAuthorRepositoryGUI authorRespository)
        {
            _countryRepository = countryRepository;
            _authorRespository = authorRespository;
        }

        public IActionResult Index()
        {
            var countries = _countryRepository.GetCountries();
            //var countries = new List<CountryDto>();
            if (countries.Count() <= 0)
            {
                ViewBag.Message = "There was a problem retrieving countries from " +
                    "the database or no country exists";
            }

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(countries);
        }

        public IActionResult GetCountryById(int countryId)
        {
            var country = _countryRepository.GetCountryById(countryId);
            //country = null;
            if (country == null)
            {
                ModelState.AddModelError("", "Error getting a country");
                ViewBag.Message = $"There was a problem retrieving country with id {countryId} " +
                    $"from the database or no country with that id exists";
                country = new CountryDto();
            }

            var authors = _countryRepository.GetAuthorsFromACountry(countryId);
            if (authors.Count() <= 0)
            {
                ViewBag.AuthorMessage = $"There are no authors from country with id {country.Id}";
            }

            var countryAuthorsViewModel = new CountryAuthorsViewModel
            {
                Country = country,
                Authors = authors
            };

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(countryAuthorsViewModel);
        }

        [HttpGet]
        public IActionResult CreateCountry()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCountry(Country country)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.PostAsJsonAsync("countries", country);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var newCountryTask = result.Content.ReadAsAsync<Country>();
                    newCountryTask.Wait();

                    var newCountry = newCountryTask.Result;
                    TempData["SuccessMessage"] = $"Country {newCountry.Name} was successfully created.";

                    return RedirectToAction("GetCountryById", new { countryId = newCountry.Id });
                }

                if ((int)result.StatusCode == 422)
                {
                    ModelState.AddModelError("", "Country Already Exists!");
                }
                else
                {
                    ModelState.AddModelError("", "Some kind of error. Country not created!");
                }
            }

            return View();
        }

        [HttpGet]
        public IActionResult UpdateCountry(int countryId)
        {
            var countryToUpdate = _countryRepository.GetCountryById(countryId);
            if (countryToUpdate == null)
            {
                ModelState.AddModelError("", "Error getting country");
                countryToUpdate = new CountryDto();
            }

            return View(countryToUpdate);
        }

        [HttpPost]
        public IActionResult UpdateCountry(Country countryToUpdate)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.PutAsJsonAsync($"countries/{countryToUpdate.Id}", countryToUpdate);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {                    
                    TempData["SuccessMessage"] = $"Country was successfully updated.";

                    return RedirectToAction("GetCountryById", new { countryId = countryToUpdate.Id });
                }

                if ((int)result.StatusCode == 422)
                {
                    ModelState.AddModelError("", "Country Already Exists!");
                }
                else
                {
                    ModelState.AddModelError("", "Some kind of error. Country not updated!");
                }
            }

            var countryDto = _countryRepository.GetCountryById(countryToUpdate.Id);
            return View(countryDto);
        }

        [HttpGet]
        public IActionResult DeleteCountry(int countryId)
        {
            var country = _countryRepository.GetCountryById(countryId);
            if (country == null)
            {
                ModelState.AddModelError("", "Some kind of error. Country doesn't exist!");
                country = new CountryDto();
            }

            return View(country);
        }

        [HttpPost]
        public IActionResult DeleteCountry(int countryId, string countryName)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.DeleteAsync($"countries/{countryId}");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = $"Country {countryName} was successfully deleted.";

                    return RedirectToAction("Index");
                }

                if ((int)result.StatusCode == 409)
                {
                    ModelState.AddModelError("", $"Country {countryName} cannot be deleted because " +
                                                $"it is used by at least one author");
                }
                else
                {
                    ModelState.AddModelError("", "Some kind of error. Country not deleted!");
                }
            }

            var countryDto = _countryRepository.GetCountryById(countryId);
            return View(countryDto);
        }
    }
}

BookGUI/Views/Authors/CreateAuthor.cshtml
@model BookApiProject.Models.Author
@{
    ViewData["Title"] = "CreateAuthor";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h1>Add new author</h1>
<form asp-controller="Authors" asp-action="CreateAuthor" method="post">
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Country">Country Name</label>
            </div>
            <div class="col-sm-3">
                @await Component.InvokeAsync("CountriesList")
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="FirstName">First Name</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="FirstName" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="LastName">Last Name</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="LastName" />
            </div>
        </div>
        <br />
        <input type="submit" value="Create Author" class="btn-sm btn btn-primary" />
    </div>
</form>

BookGUI/Views/Authors/DeleteAuthor.cshtml
@model BookApiProject.Dtos.AuthorDto
@{
    ViewData["Title"] = "DeleteAuthor";
}
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h1>Delete Author @Model.FirstName @Model.LastName ?</h1>
<br />
<form asp-controller="Authors" asp-action="DeleteAuthor" asp-route-authorFirstName="@Model.FirstName"
asp-route-authorLastName="@Model.LastName" asp-route-authorId="@Model.Id" method="post">
    <div>
        <p>
            <strong>Author Name: </strong> @Model.FirstName @Model.LastName
        </p>
        <input type="submit" value="Delete Author" class="btn btn-sm btn-danger" />
    </div>
</form>
<a asp-controller="Authors" asp-action="GetAuthorById" asp-route-authorId="@Model.Id" class="btn btn-sm btn-primary">
    Cancel
</a>

BookGUI/Views/Authors/GetAuthorById.cshtml
@model BookGUI.ViewModels.AuthorCountryBooksCategoriesViewModel
@{
    ViewData["Title"] = "GetAuthorById";
}
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h4>@ViewBag.Message</h4>
<h3 class="text-success">@ViewBag.SuccessMessage</h3>
<div>
    <h1>Author Details</h1>
    <br />
    <div>
        <p>
            <strong>Author Name:</strong> @Model.Author.FirstName @Model.Author.LastName
        </p>
        <p>
            <strong>Author's Country:</strong> @Model.Country.Name
            <a asp-controller="Countries" asp-action="GetCountryById"
               asp-route-countryId="@Model.Country.Id"> | Country Details</a>
        </p>
        <div class="form-group text-center">
            <a class="btn btn-sm btn-primary" asp-controller="Authors" asp-action="UpdateAuthor"
               asp-route-authorId="@Model.Author.Id" asp-route-CountryId="@Model.Country.Id">Update Author</a>
            <a class="btn btn-sm btn-danger" asp-controller="Authors" asp-action="DeleteAuthor"
               asp-route-authorId="@Model.Author.Id">Delete Author</a>
        </div>
    </div>
    <br /><br />
    <div>
        <h4>@ViewBag.BookMessage</h4>
        @foreach (var item in Model.BookCategories)
        {
            <div>
                <p>
                    <strong>Title:</strong>
                    <span>@item.Key.Title</span>
                    <a asp-controller="Home" asp-action="GetBookById"
                       asp-route-bookId="@item.Key.Id">Book Details</a>
                </p>
                <table>
                    <tr>
                        <th style="float:left; margin-right:15px;">Category:</th>
                        @foreach(var category in item.Value)
                        {
                            <td style="float:left; margin-right:15px;">@category.Name
                                <a asp-controller="Categories" asp-action="GetCategoryById"
                                   asp-route-categoryId="@category.Id">Category Details</a>
                            </td>
                        }
                    </tr>
                </table>
            </div>
            <br /><br />
        }
    </div>
</div>

BookGUI/Views/Authors/Index.cshtml
@model IEnumerable<BookApiProject.Dtos.AuthorDto>
@{
    ViewData["Title"] = "Index";
}
<h2>@ViewBag.Message</h2>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h3 class="text-success">@ViewBag.SuccessMessage</h3>
<div>
    <h2>List Of Authors</h2>
    <br />
    @foreach (var item in Model)
    {
        <p>
            <strong>@item.FirstName @item.LastName</strong>
            <a asp-controller="Authors" asp-action="GetAuthorById" asp-route-authorId="@item.Id"> | Details</a>
            <a asp-controller="Authors" asp-action="DeleteAuthor"  asp-route-authorId="@item.Id"> | Delete Author</a>
        </p>
    }
</div>

BookGUI/Views/Authors/UpdateAuthor.cshtml
@model BookApiProject.Models.Author
@{
    ViewData["Title"] = "UpdateAuthor";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h1>Update author</h1>
<form asp-controller="Authors" asp-action="UpdateAuthor" method="post">
    <div class="form-group">
        <input asp-for="Id" hidden />
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Country">Author's Country</label>
            </div>
            <div class="col-sm-3">
                @await Component.InvokeAsync("CountriesList")
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="FirstName">First Name</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="FirstName" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="LastName">Last Name</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="LastName" />
            </div>
        </div>
        <br />
        <input type="submit" value="Update Author" class="btn-sm btn btn-primary" />
    </div>
</form>
<a asp-controller="Authors" asp-action="GetAuthorById" asp-route-authorId="@Model.Id" class="btn btn-sm btn-primary">
    Cancel
</a>