BookGUI/Components/ReviewersListViewComponent.cs
using BookGUI.Models;
using BookGUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookGUI.Components
{
    public class ReviewersListViewComponent : ViewComponent
    {
        IReviewerRepositoryGUI _reviewerRepository;

        public ReviewersListViewComponent(IReviewerRepositoryGUI reviewerRepository)
        {
            _reviewerRepository = reviewerRepository;
        }

        public IViewComponentResult Invoke()
        {
            var reviewers = _reviewerRepository.GetReviewers().
                                                OrderBy(r => r.LastName).
                                                Select(x => new { Id = x.Id, Value = x.FirstName + " " + x.LastName});

            var reviewersList = new ReviewerSelectList
            {
                ReviewersList = new SelectList(reviewers, "Id", "Value")
            };

            return View("_ReviewersList", reviewersList);
        }
    }
}

BookGUI/Controllers/ReviewersController.cs
using BookApiProject.Dtos;
using BookApiProject.Models;
using BookGUI.Services;
using BookGUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace BookGUI.Controllers
{
    public class ReviewersController : Controller
    {
        IReviewerRepositoryGUI _reviewerRepository;
        IReviewRepositoryGUI _reviewRepository;

        public ReviewersController(IReviewerRepositoryGUI reviewerRepository, IReviewRepositoryGUI reviewRepository)
        {
            _reviewerRepository = reviewerRepository;
            _reviewRepository = reviewRepository;
        }

        public IActionResult Index()
        {
            var reviewers = _reviewerRepository.GetReviewers();

            if (reviewers.Count() <= 0)
            {
                ViewBag.Message = "There was a problem retrieving reviewers from the database or no reviewer exists";
            }

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(reviewers);
        }

        public IActionResult GetReviewerById(int reviewerId)
        {
            var reviewer = _reviewerRepository.GetReviewerById(reviewerId);
            if (reviewer == null)
            {
                ModelState.AddModelError("", "Some kind of error getting reviewer");
                ViewBag.ReviewerMessage = $"There was a problem retrieving reviewer from the database " +
                                          $"or no reviewer with id {reviewerId} exist";
                reviewer = new ReviewerDto();
            }

            var reviews = _reviewerRepository.GetReviewsByReviewer(reviewerId);
            if (reviews.Count() <= 0)
            {
                ViewBag.ReviewMessage = $"Reviewer {reviewer.FirstName} {reviewer.LastName} has no reviews";
            }

            IDictionary<ReviewDto, BookDto> reviewAndBook = new Dictionary<ReviewDto, BookDto>();
            foreach(var review in reviews)
            {
                var book = _reviewRepository.GetBookOfAReview(review.Id);
                reviewAndBook.Add(review, book);
            }

            var reviewerReviewsBooksViewModel = new ReviewerReviewsBooksViewModel
            {
                Reviewer = reviewer,
                ReviewBook = reviewAndBook
            };

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(reviewerReviewsBooksViewModel);
        }

        [HttpGet]
        public IActionResult CreateReviewer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateReviewer(Reviewer reviewer)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.PostAsJsonAsync("reviewers", reviewer);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var newReviewerTask = result.Content.ReadAsAsync<Reviewer>();
                    newReviewerTask.Wait();

                    var newReviewer = newReviewerTask.Result;
                    TempData["SuccessMessage"] = $"Reviewer {newReviewer.FirstName} {newReviewer.LastName} " +
                        $"was successfully created.";

                    return RedirectToAction("GetReviewerById", new { reviewerId = newReviewer.Id });
                }
                
                ModelState.AddModelError("", "Some kind of error. Reviewer not created!");
            }

            return View();
        }

        [HttpGet]
        public IActionResult UpdateReviewer(int reviewerId)
        {
            var reviewerToUpdate = _reviewerRepository.GetReviewerById(reviewerId);
            if (reviewerToUpdate == null)
            {
                ModelState.AddModelError("", "Error getting reviewer");
                reviewerToUpdate = new ReviewerDto();
            }

            return View(reviewerToUpdate);
        }

        [HttpPost]
        public IActionResult UpdateReviewer(Reviewer reviewerToUpdate)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.PutAsJsonAsync($"reviewers/{reviewerToUpdate.Id}", reviewerToUpdate);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = $"Reviewer was successfully updated.";

                    return RedirectToAction("GetReviewerById", new { reviewerId = reviewerToUpdate.Id });
                }
                
                ModelState.AddModelError("", "Some kind of error. Reviewer not updated!");
            }

            var reviewerDto = _reviewerRepository.GetReviewerById(reviewerToUpdate.Id);
            return View(reviewerDto);
        }

        [HttpGet]
        public IActionResult DeleteReviewer(int reviewerId)
        {
            var reviewer = _reviewerRepository.GetReviewerById(reviewerId);
            if (reviewer == null)
            {
                ModelState.AddModelError("", "Some kind of error. Reviewer doesn't exist!");
                reviewer = new ReviewerDto();
            }

            return View(reviewer);
        }

        [HttpPost]
        public IActionResult DeleteReviewer(int reviewerId, string firstName, string lastName)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.DeleteAsync($"reviewers/{reviewerId}");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    TempData["SuccessMessage"] = $"Reviewer {firstName} {lastName} was successfully deleted.";

                    return RedirectToAction("Index");
                }
                
                ModelState.AddModelError("", "Some kind of error. Reviewer not deleted!");
            }

            var reviewerDto = _reviewerRepository.GetReviewerById(reviewerId);
            return View(reviewerDto);
        }
    }
}

BookGUI/Controllers/ReviewsController.cs
using BookApiProject.Dtos;
using BookApiProject.Models;
using BookGUI.Services;
using BookGUI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace BookGUI.Controllers
{
    public class ReviewsController : Controller
    {
        IReviewRepositoryGUI _reviewRepository;
        IReviewerRepositoryGUI _reviewerRepository;
        IBookRepositoryGUI _bookRepository;

        public ReviewsController(IReviewRepositoryGUI reviewRepository, IReviewerRepositoryGUI reviewerRepository,
            IBookRepositoryGUI bookRepository)
        {
            _reviewRepository = reviewRepository;
            _reviewerRepository = reviewerRepository;
            _bookRepository = bookRepository;
        }

        public IActionResult Index()
        {
            var reviews = _reviewRepository.GetReviews();

            if (reviews.Count() <= 0)
            {
                ViewBag.Message = "There was a problem retrieving reviews from the database or no review exists";
            }

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(reviews);
        }

        public IActionResult GetReviewById(int reviewId)
        {
            var review = _reviewRepository.GetReviewById(reviewId);
            if (review == null)
            {
                ModelState.AddModelError("", "Some kind of error getting review");
                ViewBag.Message = $"There was a problem retrieving review from the " +
                                    $"database or no review with id {reviewId}  exists";
                review = new ReviewDto();
            }

            var reviewer = _reviewerRepository.GetReviewerOfAReview(reviewId);
            if (reviewer == null)
            {
                ModelState.AddModelError("", "Some kind of error getting reviewer");
                ViewBag.Message += $"There was a problem retrieving reviewer from the database " +
                                    $"or no reviewer for the review id {reviewId} exist";
                reviewer = new ReviewerDto();
            }

            var book = _reviewRepository.GetBookOfAReview(reviewId);
            if (book == null)
            {
                ModelState.AddModelError("", "Some kind of error getting book");
                ViewBag.Message += $"There was a problem retrieving book from the database " +
                                    $"or no book for the review id {reviewId} exist";
                book = new BookDto();
            }

            var reviewReviewerBookViewModel = new ReviewReviewerBookViewModel
            {
                Review = review,
                Reviewer = reviewer,
                Book = book
            };

            ViewBag.SuccessMessage = TempData["SuccessMessage"];
            return View(reviewReviewerBookViewModel);
        }

        [HttpGet]
        public IActionResult CreateReview(int bookId, string bookTitle)
        {
            ViewBag.BookId = bookId;
            ViewBag.BookTitle = bookTitle;
            return View();
        }

        [HttpPost]
        public IActionResult CreateReview(int bookId, int ReviewerId, Review review)
        {
            using (var client = new HttpClient())
            {
                var reviewerDto = _reviewerRepository.GetReviewerById(ReviewerId);
                var bookDto = _bookRepository.GetBookById(bookId);

                if(reviewerDto == null || bookDto == null || review == null)
                {
                    ModelState.AddModelError("", "Invalid book, reviewer, or review. Cannot create review!");
                    ViewBag.BookId = bookId;
                    ViewBag.BookTitle = bookDto == null ? "" : bookDto.Title;
                    return View(review);
                }

                review.Reviewer = new Reviewer
                {
                    Id = reviewerDto.Id,
                    FirstName = reviewerDto.FirstName,
                    LastName = reviewerDto.LastName
                };

                review.Book = new Book
                {
                    Id = bookDto.Id,
                    Isbn = bookDto.Isbn,
                    Title = bookDto.Title
                };

                client.BaseAddress = new Uri("http://localhost:60039/api/");
                var responseTask = client.PostAsJsonAsync("reviews", review);
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var newReviewTask = result.Content.ReadAsAsync<Review>();
                    newReviewTask.Wait();

                    var newReview = newReviewTask.Result;
                    TempData["SuccessMessage"] = $"Review for {review.Book.Title} was successfully created.";
                    return RedirectToAction("GetReviewById", new { reviewId = newReview.Id });
                }

                ModelState.AddModelError("", "Review not created");
                ViewBag.BookId = bookId;
                ViewBag.BookTitle = bookDto == null ? "" : bookDto.Title;
            }

            return View(review);
        }       

        [HttpGet]
        public IActionResult UpdateReview(int bookId, int reviewId, int ReviewerId)
        {
            var reviewDto = _reviewRepository.GetReviewById(reviewId);
            var reviewerDto = _reviewerRepository.GetReviewerOfAReview(reviewId);
            var bookDto = _bookRepository.GetBookById(bookId);

            Review review = null;

            if (reviewDto == null || reviewerDto == null || bookDto == null)
            {
                ModelState.AddModelError("", "Invalid book, reviewer, or review. Cannot update review!");
                review = new Review();
            }
            else
            {
                review = new Review
                {
                    Id = reviewDto.Id,
                    Headline = reviewDto.Headline,
                    Rating = reviewDto.Rating,
                    ReviewText = reviewDto.ReviewText,
                    Reviewer = new Reviewer
                    {
                        Id = reviewerDto.Id,
                        FirstName = reviewerDto.FirstName,
                        LastName = reviewerDto.LastName
                    },
                    Book = new Book
                    {
                        Id = bookDto.Id,
                        Title = bookDto.Title,
                        Isbn = bookDto.Isbn,
                        DatePublished = bookDto.DatePublished
                    }
                };
            }

            return View(review);
        }

        [HttpPost]
        public IActionResult UpdateReview(int ReviewerId, Review reviewToUpdate)
        {
            var reviewerDto = _reviewerRepository.GetReviewerById(ReviewerId);
            var bookDto = _bookRepository.GetBookById(reviewToUpdate.Book.Id);

            if (reviewToUpdate == null || reviewerDto == null || bookDto == null)
            {
                ModelState.AddModelError("", "Invalid book, reviewer, or review. Cannot update review!");
            }
            else
            {
                reviewToUpdate.Reviewer = new Reviewer
                {
                    Id = reviewerDto.Id,
                    FirstName = reviewerDto.FirstName,
                    LastName = reviewerDto.LastName
                };
                reviewToUpdate.Book = new Book
                {
                    Id = bookDto.Id,
                    Title = bookDto.Title,
                    Isbn = bookDto.Isbn,
                    DatePublished = bookDto.DatePublished
                };

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:60039/api/");
                    var responseTask = client.PutAsJsonAsync($"reviews/{reviewToUpdate.Id}", reviewToUpdate);
                    responseTask.Wait();

                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        TempData["SuccessMessage"] = "Review updated";
                        return RedirectToAction("GetReviewById", new { reviewId = reviewToUpdate.Id });
                    }

                    ModelState.AddModelError("", "Unexpected Error. Review Not Updated");
                }
            }

            return View(reviewToUpdate);
        }

        [HttpGet]
        public IActionResult DeleteReview(int reviewId)
        {
            var reviewDto = _reviewRepository.GetReviewById(reviewId);
            var reviewerDto = _reviewerRepository.GetReviewerOfAReview(reviewId);
            var bookDto = _reviewRepository.GetBookOfAReview(reviewId);

            Review review = null;

            if (reviewDto == null || reviewerDto == null || bookDto == null)
            {
                ModelState.AddModelError("", "Some kind of error getting review, reviewer, or book");
                review = new Review();
            }
            else
            {
                review = new Review
                {
                    Id = reviewDto.Id,
                    Headline = reviewDto.Headline,
                    Rating = reviewDto.Rating,
                    ReviewText = reviewDto.ReviewText,
                    Reviewer = new Reviewer
                    {
                        Id = reviewerDto.Id,
                        FirstName = reviewerDto.FirstName,
                        LastName = reviewerDto.LastName
                    },
                    Book = new Book
                    {
                        Id = bookDto.Id,
                        Title = bookDto.Title,
                        Isbn = bookDto.Isbn,
                        DatePublished = bookDto.DatePublished
                    }
                };

BookGUI/Views/Reviews/CreateReview.cshtml
@model BookApiProject.Models.Review
@{
    ViewData["Title"] = "CreateReview";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h1>Add new review for @ViewBag.BookTitle</h1>
<form asp-controller="Reviews" asp-action="CreateReview" asp-route-bookId="@ViewBag.BookId" method="post">
    <div class="form-group">
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Reviewer">Reviewer Name</label>
            </div>
            <div class="col-sm-3">
                @await Component.InvokeAsync("ReviewersList")
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Headline">Review Headline</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="Headline" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Rating">Review Rating</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="Rating" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="ReviewText">Review:</label>
            </div>
            <div class="col-sm-3">
                <textarea asp-for="ReviewText" style="min-width:200px; min-height:200px;"></textarea>
            </div>
        </div>
        <br />
        <input type="submit" value="Create Review" class="btn-sm btn btn-primary" />
    </div>
</form>

BookGUI/Views/Reviews/DeleteReview.cshtml
@model BookApiProject.Models.Review
@{
    ViewData["Title"] = "DeleteReview";
}
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div>
    <h2>Do you want to delete this review?</h2>
    <br />
    <form asp-controller="Reviews" asp-action="DeleteReview" asp-route-reviewId="@Model.Id" method="post">
        <div>
            <p>
                <strong>Reviewer Name:</strong><span>
                    @Model.Reviewer.FirstName @Model.Reviewer.LastName
                </span>
            </p>
            <p>
                <strong>Book Title:</strong><span>
                    @Model.Book.Title
                </span>
            </p>
            <p>
                <strong>Review Headline:</strong><span> @Model.Headline </span>
            </p>
            <p>
                <strong>Review Rating:</strong><span> @Model.Rating </span>
            </p>
            <p>
                <strong>Review Text:</strong><span>@Model.ReviewText </span>
            </p>
        </div>
        <input type="submit" value="Delete Review" class="btn btn-sm btn-danger" />
    </form>
    <br />
        <a class="btn btn-sm btn-primary" asp-controller="Reviews" asp-action="GetReviewById"
           asp-route-reviewId="@Model.Id">Cancel</a>
</div>

BookGUI/Views/Reviews/GetReviewById.cshtml
@model BookGUI.ViewModels.ReviewReviewerBookViewModel
@{
    ViewData["Title"] = "GetReviewById";
}
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h4>@ViewBag.Message</h4>
<h3 class="text-success">@ViewBag.SuccessMessage</h3>
<div>
    <h2>Review Details for @Model.Book.Title</h2>
    <br />
    <div>
        <p>
            <strong>Reviewer Name:</strong><span>
                @Model.Reviewer.FirstName @Model.Reviewer.LastName

                <a asp-controller="Reviewers" asp-action="GetReviewerById"
                   asp-route-reviewerId="@Model.Reviewer.Id">| Reviewer Details |</a>
            </span>
        </p>
        <p>
            <strong>Book Title:</strong><span>
                @Model.Book.Title

                <a asp-controller="Home" asp-action="GetBookById"
                   asp-route-bookId="@Model.Book.Id"> | Book Details |</a>
            </span>
        </p>
        <p>
            <strong>Review Headline:</strong><span> @Model.Review.Headline </span>
        </p>
        <p>
            <strong>Review Rating:</strong><span> @Model.Review.Rating </span>
        </p>
        <p>
            <strong>Review Text:</strong><span>@Model.Review.ReviewText </span>
        </p>
    </div>
    <br /><br />
    <div class="form-group text-center">
        <a class="btn btn-sm btn-primary" asp-controller="Reviews" asp-action="UpdateReview" 
        asp-route-bookId ="@Model.Book.Id" asp-route-reviewId="@Model.Review.Id" 
        asp-route-ReviewerId="@Model.Reviewer.Id">Update Review</a>
        <a class="btn btn-sm btn-danger" asp-controller="Reviews" asp-action="DeleteReview"
           asp-route-reviewId="@Model.Review.Id">Delete Review</a>
    </div>
</div>

BookGUI/Views/Reviews/Index.cshtml
@model IEnumerable<BookApiProject.Dtos.ReviewDto>
@{
    ViewData["Title"] = "Index";
}
<h2>@ViewBag.Message</h2>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h3 class="text-success">@ViewBag.SuccessMessage</h3>
<div>
    <h2>List Of Reviews</h2>
    <br />
    @foreach (var item in Model)
    {
        <p>
            <strong>@item.Headline</strong>
            <a asp-controller="Reviews" asp-action="GetReviewById" asp-route-reviewId="@item.Id"> | Details</a>
            <a asp-controller="Reviews" asp-action="DeleteReview"  asp-route-reviewId="@item.Id"> | Delete Review</a>
        </p>
    }
</div>

BookGUI/Views/Reviews/UpdateReview.cshtml
@model BookApiProject.Models.Review
@{
    ViewData["Title"] = "UpdateReview";
}

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h1>Update review for @Model.Book.Title</h1>
<form asp-controller="Reviews" asp-action="UpdateReview" method="post">
    <div class="form-group">
        <input asp-for="Book.Id" hidden />
        <input asp-for="Id" hidden />
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Reviewer">Reviewer Name</label>
            </div>
            <div class="col-sm-3">
                @await Component.InvokeAsync("ReviewersList")
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Headline">Review Headline</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="Headline" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="Rating">Review Rating</label>
            </div>
            <div class="col-sm-3">
                <input asp-for="Rating" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <label asp-for="ReviewText">Review:</label>
            </div>
            <div class="col-sm-3">
                <textarea asp-for="ReviewText" style="min-width:200px; min-height:200px;"></textarea>
            </div>
        </div>
        <br />
        <input type="submit" value="Update Review" class="btn-sm btn btn-primary" />
    </div>
</form>
<a asp-controller="Reviews" asp-action="GetReviewById" asp-route-reviewId="@Model.Id" class="btn btn-sm btn-primary">
Cancel
</a>